# IBM VPC On-Demand VSI with Docker
# Purpose: Spin up/down IBM Cloud VPC VSI for lab work

# Data source for Ubuntu image
data "ibm_is_image" "ubuntu" {
  name = "ibm-ubuntu-22-04-3-minimal-amd64-1"
}

# Data source for SSH key (existing)
data "ibm_is_ssh_key" "lab_key" {
  name = var.ssh_key_name
}

# VPC
resource "ibm_is_vpc" "ondemand_vpc" {
  name = "n8n-lab-vpc"
  tags = ["n8n-lab", "on-demand"]
}

# Subnet
resource "ibm_is_subnet" "ondemand_subnet" {
  name            = "n8n-lab-subnet"
  vpc             = ibm_is_vpc.ondemand_vpc.id
  zone            = "${var.ibm_region}-1"
  ipv4_cidr_block = "10.240.0.0/24"
  tags            = ["n8n-lab", "on-demand"]
}

# Security Group to allow SSH and HTTP
resource "ibm_is_security_group" "ondemand_sg" {
  name = "n8n-lab-sg"
  vpc  = ibm_is_vpc.ondemand_vpc.id
  tags = ["n8n-lab", "on-demand"]
}

resource "ibm_is_security_group_rule" "allow_ssh" {
  group     = ibm_is_security_group.ondemand_sg.id
  direction = "inbound"
  remote    = "0.0.0.0/0"
  tcp {
    port_min = 22
    port_max = 22
  }
}

resource "ibm_is_security_group_rule" "allow_outbound" {
  group     = ibm_is_security_group.ondemand_sg.id
  direction = "outbound"
  remote    = "0.0.0.0/0"
}

# Public Gateway for internet access
resource "ibm_is_public_gateway" "ondemand_gateway" {
  name = "n8n-lab-gateway"
  vpc  = ibm_is_vpc.ondemand_vpc.id
  zone = "${var.ibm_region}-1"
  tags = ["n8n-lab", "on-demand"]
}

# Attach gateway to subnet
resource "ibm_is_subnet_public_gateway_attachment" "ondemand_gateway_attachment" {
  subnet         = ibm_is_subnet.ondemand_subnet.id
  public_gateway = ibm_is_public_gateway.ondemand_gateway.id
}

# Cloud-init script to install Docker and create README
locals {
  cloud_init = <<-EOT
    #cloud-config
    package_update: true
    package_upgrade: true
    packages:
      - ca-certificates
      - curl
      - gnupg
    write_files:
      - path: /home/ubuntu/README.md
        owner: ubuntu:ubuntu
        permissions: '0644'
        content: |
          # IBM VPC VSI - n8n Lab Environment

          ## Instance Information
          - **Created**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          - **Purpose**: On-demand lab environment for n8n + Terraform automation
          - **Managed by**: n8n workflows via Terraform
          - **Image**: Custom n8n-lab-vsi image (if from saved image)

          ## Pre-installed Software
          - Ubuntu 22.04 LTS
          - Docker CE (with docker-compose)
          - SSH access configured

          ## Usage
          This VSI is part of an on-demand infrastructure automation system.

          **Workflows available:**
          1. Connectivity Test - Verify VSI is accessible
          2. Image Capture - Save current state as custom image
          3. Tear Down - Destroy VSI and stop billing

          ## Cost Optimization
          Remember to tear down this VSI when not in use to stop hourly billing!

          **Cost**: ~$0.10/hour when running

          ---
          Generated by n8n-lab automation system
    runcmd:
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list
      - apt-get update
      - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
      - systemctl start docker
      - systemctl enable docker
      - usermod -aG docker ubuntu
      - sed -i "s/\$(date -u +\"%Y-%m-%d %H:%M:%S UTC\")/$(date -u +"%Y-%m-%d %H:%M:%S UTC")/" /home/ubuntu/README.md
    final_message: "Docker installation complete! README.md created in /home/ubuntu/"
  EOT
}

# VSI Instance
resource "ibm_is_instance" "ondemand_vsi" {
  name    = var.instance_name
  image   = data.ibm_is_image.ubuntu.id
  profile = var.instance_profile
  tags    = ["n8n-lab", "on-demand", "docker"]

  primary_network_interface {
    subnet          = ibm_is_subnet.ondemand_subnet.id
    security_groups = [ibm_is_security_group.ondemand_sg.id]
  }

  vpc  = ibm_is_vpc.ondemand_vpc.id
  zone = "${var.ibm_region}-1"
  keys = [data.ibm_is_ssh_key.lab_key.id]

  user_data = local.cloud_init
}

# Floating IP for public access
resource "ibm_is_floating_ip" "ondemand_fip" {
  name   = "n8n-lab-fip"
  target = ibm_is_instance.ondemand_vsi.primary_network_interface[0].id
  tags   = ["n8n-lab", "on-demand"]
}

# Outputs
output "vsi_id" {
  value       = ibm_is_instance.ondemand_vsi.id
  description = "VSI Instance ID"
}

output "public_ip" {
  value       = ibm_is_floating_ip.ondemand_fip.address
  description = "Public IP address"
}

output "private_ip" {
  value       = ibm_is_instance.ondemand_vsi.primary_network_interface[0].primary_ipv4_address
  description = "Private IP address"
}

output "vpc_id" {
  value       = ibm_is_vpc.ondemand_vpc.id
  description = "VPC ID"
}

output "ssh_command" {
  value       = "ssh -i ${var.ssh_key_path} ubuntu@${ibm_is_floating_ip.ondemand_fip.address}"
  description = "SSH command to connect"
}
